/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppKeywordsRouteImport } from './routes/_app.keywords'
import { Route as AppDigestRouteImport } from './routes/_app.digest'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComparisonRouteImport } from './routes/_app.comparison'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKeywordsRoute = AppKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestRoute = AppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComparisonRoute = AppComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/comparison': typeof AppComparisonRoute
  '/dashboard': typeof AppDashboardRoute
  '/digest': typeof AppDigestRoute
  '/keywords': typeof AppKeywordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/comparison': typeof AppComparisonRoute
  '/dashboard': typeof AppDashboardRoute
  '/digest': typeof AppDigestRoute
  '/keywords': typeof AppKeywordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/comparison': typeof AppComparisonRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/digest': typeof AppDigestRoute
  '/_app/keywords': typeof AppKeywordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/comparison'
    | '/dashboard'
    | '/digest'
    | '/keywords'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/comparison'
    | '/dashboard'
    | '/digest'
    | '/keywords'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/comparison'
    | '/_app/dashboard'
    | '/_app/digest'
    | '/_app/keywords'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/keywords': {
      id: '/_app/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AppKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digest': {
      id: '/_app/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AppDigestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparison': {
      id: '/_app/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof AppComparisonRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComparisonRoute: typeof AppComparisonRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDigestRoute: typeof AppDigestRoute
  AppKeywordsRoute: typeof AppKeywordsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComparisonRoute: AppComparisonRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDigestRoute: AppDigestRoute,
  AppKeywordsRoute: AppKeywordsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
